version: '3'
services:
  nginx-certbot:
    image: 3dwardsharp/nginx-certbot:latest
    restart: always
    environment:
      - DOMAINS=api.marshcoop.org
      - EMAIL=hello@marshcoop.org
      - BASE_SERVER=api.marshcoop.org
      - BASE_SERVER_PROXY=api
      - BASE_SERVER_PORT=3000
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    links:
      - api
    network_mode: bridge
    ports:
      - '80:80'
      - '443:443'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  api:
    image: 3dwardsharp/sorta-cart-server:latest
    restart: always
    volumes:
      - logvolume01:/var/log
    links:
      - pg
    network_mode: bridge
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - PG_DATABASE_NAME=${PG_DATABASE_NAME}
      - PG_DATABASE_USER=${PG_DATABASE_USER}
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD}
      - PG_DATABASE_HOST=pg
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAIL_GOES_TO=hello@marshcoop.org
      - SQUARE_TOKEN=${SQUARE_TOKEN}
      - SQUARE_URL=${SQUARE_URL}
      - SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID}
  pg:
    image: postgres:12-alpine
    restart: always
    network_mode: bridge
    environment:
      POSTGRES_USER: ${PG_DATABASE_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}
      PGDATA: /pgdata
    volumes:
      - pgdata:/pgdata
      - logvolume01:/var/log
volumes:
  logvolume01: {}
  pgdata: {}
  letsencrypt: {}
