version: '3'
services:
  pg:
    image: postgres:12-alpine
    restart: always
    network_mode: bridge
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PG_DATABASE_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}
      PGDATA: /pgdata
    volumes:
      - pgdata:/pgdata
      - logvolume01:/var/log
volumes:
  logvolume01: {}
  pgdata: {}
